import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { WebSocketProvider } from "@/provider/WebSockerProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <WebSocketProvider>
        <Navbar />
         <div className="flex h-screen ">
         
          
      {/* Sidebar for large screens */}
      {/* <div className="hidden md:flex md:w-72 shadow-md">
        <Sidebar />
      </div> */}
      
      
      
      {/* Main content */}
      <div className="flex-1 p-4">
      
        {children}
      </div>
    </div>
    </WebSocketProvider>

      </body>
    </html>
  );
}
